### ISSUE TITLE
 Apresentação Terça, 29/11

### ISSUE THREAD

**Issue by fsantanna** [HenriqueMaiani/EDL#4]
Henrique, sua apresentação sobre C# ficou para a próxima terça-feira, ok?

**Comment by HenriqueMaiani** [comment]
Opa ok professor obrigado posso melhorar os slides?
Abraços

Obter o Outlook para Android<https://aka.ms/ghei36>



On Sat, Nov 26, 2016 at 9:10 AM -0200, "fsantanna" <notifications@github.com<mailto:notifications@github.com>> wrote:


Henrique, sua apresentação sobre C# ficou para a próxima terça-feira, ok?

**Comment by fsantanna** [comment]
deve
